version: '3.8'

services:
  backend:
    build: ./amzn-extension-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./amzn-extension-frontend
    ports:
      - "80:80"
